config/routes.rb
MonitorTiming::Application.routes.draw do

	get "tickets/:id/answer" => "tickets#answer"

  resources :tickets do
		resources :calls end

  resources :subjects

  resources :calls

  resources :sectors

  devise_for :users

  resources :users

  root :to => "home#index"

end

app/models/sector.rb
class Sector < ActiveRecord::Base
  has_many :users
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  # GET /sectors
  # GET /sectors.xml
  def index
    @sectors = Sector.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sectors }
    end
  end

  # GET /sectors/1
  # GET /sectors/1.xml
  def show
    @sector = Sector.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sector }
    end
  end

  # GET /sectors/new
  # GET /sectors/new.xml
  def new
    @sector = Sector.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sector }
    end
  end

  # GET /sectors/1/edit
  def edit
    @sector = Sector.find(params[:id])
  end

  # POST /sectors
  # POST /sectors.xml
  def create
    @sector = Sector.new(params[:sector])

    respond_to do |format|
      if @sector.save
        format.html { redirect_to(@sector, :notice => 'Sector was successfully created.') }
        format.xml  { render :xml => @sector, :status => :created, :location => @sector }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sector.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sectors/1
  # PUT /sectors/1.xml
  def update
    @sector = Sector.find(params[:id])

    respond_to do |format|
      if @sector.update_attributes(params[:sector])
        format.html { redirect_to(@sector, :notice => 'Sector was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sector.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sectors/1
  # DELETE /sectors/1.xml
  def destroy
    @sector = Sector.find(params[:id])
    @sector.destroy

    respond_to do |format|
      format.html { redirect_to(sectors_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/sectors/_form.html.erb
<%= form_for(@sector) do |f| %>
  <% if @sector.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sector.errors.count, "error") %> prohibited this sector from being saved:</h2>

      <ul>
      <% @sector.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sectors/edit.html.erb
<h1>Editing sector</h1>

<%= render 'form' %>

<%= link_to 'Show', @sector %> |
<%= link_to 'Back', sectors_path %>

app/views/sectors/index.html.erb
<h1>Listing sectors</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sectors.each do |sector| %>
  <tr>
    <td><%= sector.name %></td>
    <td><%= link_to 'Show', sector %></td>
    <td><%= link_to 'Edit', edit_sector_path(sector) %></td>
    <td><%= link_to 'Destroy', sector, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sector', new_sector_path %>

app/views/sectors/new.html.erb
<h1>New sector</h1>

<%= render 'form' %>

<%= link_to 'Back', sectors_path %>

app/views/sectors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sector.name %>
</p>


<%= link_to 'Edit', edit_sector_path(@sector) %> |
<%= link_to 'Back', sectors_path %>