config/routes.rb
MonitorTiming::Application.routes.draw do

	get "tickets/:id/answer" => "tickets#answer"

  resources :tickets do
		resources :calls end

  resources :subjects

  resources :calls

  resources :sectors

  devise_for :users

  resources :users

  root :to => "home#index"

end

app/models/call.rb
class Call < ActiveRecord::Base
  belongs_to :user
  belongs_to :ticket
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  # GET /calls
  # GET /calls.xml
  def index
    @calls = Call.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @calls }
    end
  end

  # GET /calls/1
  # GET /calls/1.xml
  def show
    @call = Call.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @call }
    end
  end

  # GET /calls/new
  # GET /calls/new.xml
  def new
    @call = Call.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @call }
    end
  end

  # GET /calls/1/edit
  def edit
    @call = Call.find(params[:id])
  end

  # POST /calls
  # POST /calls.xml
  def create

    @ticket = Ticket.find(params[:ticket_id])
    @call = @ticket.calls.create(params[:call])
    redirect_to ticket_path(@ticket)


#    respond_to do |format|
#      if @call.save
#        format.html { redirect_to(@call, :notice => 'Call was successfully created.') }
#        format.xml  { render :xml => @call, :status => :created, :location => @call }
#      else
#        format.html { render :action => "new" }
#        format.xml  { render :xml => @call.errors, :status => :unprocessable_entity }
#      end
#    end
  end

  # PUT /calls/1
  # PUT /calls/1.xml
  def update
    @call = Call.find(params[:id])

    respond_to do |format|
      if @call.update_attributes(params[:call])
        format.html { redirect_to(@call, :notice => 'Call was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @call.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1
  # DELETE /calls/1.xml
  def destroy
    @call = Call.find(params[:id])
    @call.destroy

    respond_to do |format|
      format.html { redirect_to(calls_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/_form.html.erb
<%= form_for(@call) do |f| %>
  <% if @call.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
      <% @call.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_area :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calls/edit.html.erb
<h1>Editing call</h1>

<%= render 'form' %>

<%= link_to 'Show', @call %> |
<%= link_to 'Back', calls_path %>

app/views/calls/index.html.erb
<h1>Listing calls</h1>

<table>
  <tr>
    <th>Answer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @calls.each do |call| %>
  <tr>
    <td><%= call.answer %></td>
    <td><%= link_to 'Show', call %></td>
    <td><%= link_to 'Edit', edit_call_path(call) %></td>
    <td><%= link_to 'Destroy', call, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Call', new_call_path %>

app/views/calls/new.html.erb
<h1>New call</h1>

<%= render 'form' %>

<%= link_to 'Back', calls_path %>

app/views/calls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Answer:</b>
  <%= @call.answer %>
</p>


<%= link_to 'Edit', edit_call_path(@call) %> |
<%= link_to 'Back', calls_path %>