config/routes.rb
MonitorTiming::Application.routes.draw do

	get "tickets/:id/answer" => "tickets#answer"

  resources :tickets do
		resources :calls end

  resources :subjects

  resources :calls

  resources :sectors

  devise_for :users

  resources :users

  root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tickets</title>
	<link href="images/icone.png" rel="shortcut icon"/>
    <%= stylesheet_link_tag 'jquery-ui', 'active_admin', 'form', 'override'%>
  </head>
  <body>
    <div id="wrapper">
      <div id="header">
        <h1 id="site_title">Tickets</h1>
        <ul id="tabs">
          <li <%= raw 'class="current"' if controller_name == 'tickets' %>><%= link_to t('models.ticket'), tickets_path %></li>
          <li <%= raw 'class="current"' if controller_name == 'sectors' %>><%= link_to t('models.sector'), sectors_path %></li>
          <li <%= raw 'class="current"' if controller_name == 'subject' %>><%= link_to t('models.subject'), subjects_path %></li>
          <li <%= raw 'class="current"' if controller_name == 'calls' %>><%= link_to t('models.call'), calls_path %></li>
          <li <%= raw 'class="current"' if controller_name == 'users'%>><%= link_to t('models.user'), users_path%></li>
        </ul>
      </div>
      <div id="title_bar">
        <h2 id="page_title">
          <%= t '.dashboard' %> &rsaquo; <%= t 'models.'+controller_name.singularize %>
        </h2>
        <div class="action_items">
          <%= yield :toolbar %>
        </div>
      </div>
      <div id="content" class="<%= content_for?(:sidebar) ? 'with_sidebar' : 'without_sidebar' %>">
        <div id="main_content_wrapper">
          <div id="main_content">
            <%= yield %>
          </div>
        </div>
        <div id="sidebar">
          <div class="sidebar_section panel" id="filters_sidebar_section">
            <%= yield :sidebar %>
          </div>
        </div>
      </div>
    </div>
    <div id="footer">
    </div>
    <%= javascript_include_tag 'jquery.min', 'jquery-ui.min', 'jquery_ujs', :cache => 'cache/application' %>
    <%= csrf_meta_tag %>
  </body>
</html>